server:
  port: 8999
#  context-path: /uaa
#  use-forward-headers: false

spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_demo?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: alan
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://alan:cifnews-train@localhost:8761/eureka



security:
  oauth2:
    resource:
      filter-order: 3

logging:
  level.org.springframework.security: DEBUG




