server:
  port: 8081
  context-path: /uaa
  use-forward-headers: false

spring:
  application:
    name: uaa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_demo?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: alan

security:
  basic:
    enabled: false
  user:
    password: alan
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://alan:cifnews-train@localhost:8761/eureka



