server:
  port: 9999
spring:
  application:
    name: zuul-gateway-service
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://alan:cifnews-train@service-registry:8761/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
   order-service:
      path: /order-service/**
      serviceId: order-service
   product-service:
      path: /product-service/**
      serviceId: product-service
