eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://alan:cifnews-train@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

