spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: alan

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://alan:cifnews-train@localhost:8761/eureka


