server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://alan:cifnews-train@localhost:8761/eureka